//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyTrackerApp.Assests.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangaugeResource_Dutch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangaugeResource_Dutch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyTrackerApp.Assests.Language.LangaugeResource.Dutch", typeof(LangaugeResource_Dutch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string BtnDashboard {
            get {
                return ResourceManager.GetString("BtnDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoofd.
        /// </summary>
        internal static string BtnMain {
            get {
                return ResourceManager.GetString("BtnMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opties.
        /// </summary>
        internal static string BtnOptions {
            get {
                return ResourceManager.GetString("BtnOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samenvatting.
        /// </summary>
        internal static string BtnSummary {
            get {
                return ResourceManager.GetString("BtnSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        internal static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuratie is al ingesteld op .
        /// </summary>
        internal static string ChangeFailed {
            get {
                return ResourceManager.GetString("ChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies taal.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geld wissen.
        /// </summary>
        internal static string ClearMoney {
            get {
                return ResourceManager.GetString("ClearMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuta veranderd.
        /// </summary>
        internal static string CurrencyChanged {
            get {
                return ResourceManager.GetString("CurrencyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit is hoe dichtbij je bent bij je doel.
        /// </summary>
        internal static string GoalCloseText {
            get {
                return ResourceManager.GetString("GoalCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal veranderd.
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen verandering.
        /// </summary>
        internal static string NoChange {
            get {
                return ResourceManager.GetString("NoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, je heb nog geen doel.
        /// </summary>
        internal static string NoGoalText {
            get {
                return ResourceManager.GetString("NoGoalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start de applicatie opnieuw om de instelling te laten werken.
        /// </summary>
        internal static string SettingChanged {
            get {
                return ResourceManager.GetString("SettingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start geminimaliseerd.
        /// </summary>
        internal static string StartMinimized {
            get {
                return ResourceManager.GetString("StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, wat een uitdagend jaar is het geweest! 😔
        ///Terugkijkend op de afgelopen maanden is het duidelijk dat dit jaar zijn deel van financiële hindernissen heeft gepresenteerd. 💸 Ondanks de moeilijkheden is het cruciaal om deze ervaringen te erkennen en ervan te leren. Laten we in detail ingaan op de financiële reis gedurende {ExpenseFileCount} maanden, met totale uitgaven die zich opstapelen tot {TotaalSum}.
        ///
        ///Gedurende deze periode werd de reis gekenmerkt door onverwachte wendingen. Elke maand bracht zijn u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SummaryBad {
            get {
                return ResourceManager.GetString("SummaryBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow, wat een ongelooflijk jaar is het geweest! 🎉
        ///Ik ben opgetogen om te delen dat deze financiële reis ronduit fantastisch is geweest. 🚀
        ///Gedurende het jaar hebben zorgvuldige tracking en slimme financiële beslissingen de weg geëffend voor een financiële toekomst vol licht. 💰
        ///
        ///In de loop van {ExpenseFileCount} maanden is de reis verhelderend geweest. Elke maand bracht zijn eigen set uitdagingen en overwinningen met zich mee, die uiteindelijk hebben bijgedragen aan het algehele financiële verhaal. De t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SummaryGood {
            get {
                return ResourceManager.GetString("SummaryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type nieuw hier.
        /// </summary>
        internal static string TypeNewHere {
            get {
                return ResourceManager.GetString("TypeNewHere", resourceCulture);
            }
        }
    }
}
